### get-notes > 200
GET localhost:5000/get-notes
Authorization: {"username":"s.vandegar@student.helmo.be", "password":"pppppppp"}

### get-notes failled > 401
GET localhost:5000/get-notes
Authorization: {"username":"_s.vandegar@student.helmo.b

### get-notes-to-revise > 200
GET localhost:5000/get-notes-to-revise
Authorization: {"username":"seraphin.vandegar@student.howest.be", "password":"pppppppp"}
