
### cards to revise > 200
GET localhost:5000/cards-to-revise
Authorization: {"username":"s.vandegar@student.helmo.be", "password":"pppppppp"}

### cards > 200
POST localhost:5000/cards
Authorization: {"username":"s.vandegar@student.helmo.be", "password":"pppppppp"}
Content-Type: application/json

[{
  "native" : "Bonjour",
  "foreign" : "Hallo3",
  "tags" : []
},{
  "native" : "Bonjour",
  "foreign" : "Hallo4",
  "tags" : []
}]

### cards > 200
GET localhost:5000/cards
Authorization: {"username":"s.vandegar@student.helmo.be", "password":"pppppppp"}


### cards to revise > 200
PATCH localhost:5000/cards-to-revise?id=1733151780893&ease=2&timer_started=1733174593.5337138
Authorization: {"username":"s.vandegar@student.helmo.be", "password":"pppppppp"}

### delete cards > 200
DELETE localhost:5000/cards
Authorization: {"username":"s.vandegar@student.helmo.be", "password":"pppppppp"}
Content-Type: application/json

[1733000565236]


